;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        indent-for-tab-command
        kill-region
        org-self-insert-command
        rspec-verify
        rspec-verify-single
        ruby-tools-interpolate
        wdired--self-insert
        wdired-finish-edit
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        duplicate-current-line
        markdown-outdent-or-delete
        purescript-indentation-delete-backward-char
        ))
