(when (and (fboundp 'treesit-available-p)
           (or (fboundp 'treesit-ready-p)
               (require 'treesit nil t))
           (treesit-available-p))
  (setq treesit-extra-load-path (list (expand-file-name "tree-sitter/" user-emacs-directory)))

  (setq treesit-language-source-alist
     '((bash "https://github.com/tree-sitter/tree-sitter-bash")
       (css "https://github.com/tree-sitter/tree-sitter-css")
       (elisp "https://github.com/Wilfred/tree-sitter-elisp")
       (go "https://github.com/tree-sitter/tree-sitter-go")
       (haskell "https://github.com/tree-sitter/tree-sitter-haskell")
       (html "https://github.com/tree-sitter/tree-sitter-html")
       (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
       (json "https://github.com/tree-sitter/tree-sitter-json")
       (make "https://github.com/alemuller/tree-sitter-make")
       (markdown "https://github.com/ikatyang/tree-sitter-markdown")
       (purescript "https://github.com/postsolar/tree-sitter-purescript")
       (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
       (rust "https://github.com/tree-sitter/tree-sitter-rust")
       (toml "https://github.com/tree-sitter/tree-sitter-toml")
       (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
       (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
       (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

  (defvar dodecaphonic/treesit-modes
    '((css        . (css-mode . css-ts-mode))
      (go         . (go-mode . go-ts-mode))
      (html       . (html-mode . html-ts-mode))
      (javascript . (js-mode . js-ts-mode))
      (json       . (json-mode . json-ts-mode))
      (python     . (python-mode . python-ts-mode))
      (ruby       . (ruby-mode . ruby-ts-mode))
      (rust       . (rust-mode . rust-ts-mode))
      (toml       . (conf-toml-mode . toml-ts-mode))
      (typescript . (typescript-mode . typescript-ts-mode))
      (tsx        . (typescript-mode . tsx-ts-mode))
      (yaml       . (yaml-mode . yaml-ts-mode)))
    "Alist of (language . (old-mode . ts-mode)) for tree-sitter.")

  (dolist (entry dodecaphonic/treesit-modes)
    (let ((lang (car entry))
          (pair (cdr entry)))
      (when (treesit-language-available-p lang)
        (add-to-list 'major-mode-remap-alist pair))))

  (defun dodecaphonic/treesit-install-all ()
    "Install all tree-sitter grammar languages."
    (interactive)
    (dolist (entry dodecaphonic/treesit-modes)
      (treesit-install-language-grammar (car entry)))))
